# at least one part
parts:
  - label: backup_1
    dev: /dev/sdc1
    path: /mnt/backups/disk_1
  - label: backup_2
    dev: /dev/sdd1
    path: /mnt/backups/disk_2
    
notifications: true
  
policy:
  daily_retention: 3
  weekly_retention: 2
  monthly_retention: 3
  
backups:
  infrastructure:
    postgresql:
      global: true
      all_db: false
      config: true # /etc/postgresql
  services:
    - label: gitea # mandatory
      systemd: gitea # mandatory
      # at least one argument
      docker_compsose: /opt/gitea # not mandatory (copy .yaml and *.env.* files)
      config: /etc/gitea # not mandatory
      data:
       files: /var/lib/gitea # not mandatory
       pg-db: giteadb
      logs: /var/log/gitea  # not mandatory
      
    - label: linkwarden
      systemd: linkwarden 
      docker_compsose: /opt/linkwarden
      data:
       files: /var/lib/linkwarden
       pg-db: linkwardendb
      
    - label: nginx
      systemd: nginx
      config: /etc/nginx
    
    - label: opencloud
      systemd: opencloud
      config: /etc/opencloud
      data:
        files: /var/lib/opencloud
  paths:
    - label: user_fotos
      path: /home/user/fotos
    - label: history 
      path: /srv/history/
  etc: true # exclude folder from services if config start with /etc/
  certificates: false