# at least one part
parts:
  - label: backup_1
    dev: /dev/sdc1
    path: /mnt/backups/disk_1
  - label: backup_2
    dev: /dev/sdd1
    path: /mnt/backups/disk_2
    
notifications: true
  
policy:
  daily_retention: 3
  weekly_retention: 2
  monthly_retention: 3
  
backups:
  infrastructure:
    postgresql:
      global: true
      all_db: false
      config: true # /etc/postgresql
    nginx:
      config: true # /etc/nginx
      certificates: true # certificates that used in sited-available
    redis:
      config: true # /etc/redis
    meilisearch:
      config: true # /etc/meilisearch
      data: true # /var/lib/meilisearch
  services:
    - label: gitea # mandatory
      systemd:
        name: gitea
        podman:
          user: admin
          uid: 1000
      containers:
        compose: /opt/gitea # not mandatory (copy .yaml and *.env.* files)
      config: /etc/gitea # not mandatory
      data:
       files: /var/lib/gitea # not mandatory
       pg-db: giteadb
      logs: /var/log/gitea  # not mandatory
      
    - label: linkwarden
      systemd: 
        name: podman-compose@linkwarden
        podman:
          user: admin
          uid: 1000
      containers:
        compose: /opt/linkwarden
      data:
       files: /var/lib/linkwarden
       pg-db: linkwardendb
    
    - label: opencloud
      systemd: 
        name: opencloud
      config: /etc/opencloud
      data:
        files: /var/lib/opencloud
  paths:
    - label: user_fotos
      path: /home/user/fotos
    - label: history 
      path: /srv/history/
  etc: true # exclude folders from services if config start with /etc/ and infrastructure configs