parts:
  - label: backup_1
    path: /mnt/backups/disk_1
    dev: /dev/sdc1
  - label: backup_2
    path: /mnt/backups/disk_2
    dev: /dev/sdd1
  
policy:
  daily_retention: 3
  weekly_retention: 2
  monthly_retention: 3
  
backups:
  postgresql: true
  paths:
    - path: /home/user/photos
    - label: service_1
      systemd: service_1
      path: /var/lib/service_1
    - label: service_2
      systemd: service_2
      path: /var/lib/service_2
  etc: true
  docker: true
  certificates: false

notifications: true
  